@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFhYWZmMWMxLTFiODEtNDY5OC04ZDgzLWE2YmI5ZjhkYWI5NyIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzEwMjE4MTE5LCJleHAiOjE3MTA1NjM3MTl9.w2mVBIuLgnONQa9O6SvK226VPqEePpX5DZFmRWy4wg0

###
POST http://localhost:5005/register
Content-Type: application/json

{
    "username": "user",
    "password": "User1234!",
    "fullname": "user",
    "phone": "08123456783",
    "email": "user@gmail.com"
}

###
POST http://localhost:5005/login
Content-Type: application/json

{
    "username" : "user",
    "password" : "User1234!"
}

###
GET http://localhost:5005/fetch
Authorization: Bearer {{token}}
Content-Type: application/json


###
GET http://localhost:5005/user
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST http://localhost:5005/patient
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nik": "1234567891234567",
    "fullname": "Oke Gas",
    "place_birth": "Oke Gas",
    "date_birth": "01-01-2024",
    "gender": "Oke Gas",
    "address": "Oke Gas",
    "work": "Oke Gas",
    "phone": "012345678921",
    "id_user": "Oke Gas"
}

###
GET http://localhost:5005/patient
Authorization: Bearer {{token}}
Content-Type: application/json
