@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIxNDc0ODQ2LTJjMTItNGU3My05OTRhLWRlMjcxZWVmZjA2ZSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcxNjk3ODc5MywiZXhwIjoxNzE3MzI0MzkzfQ.z5uY5ih4PMFQa-cNWmEQcK8TZrE8o2OoQMhXOZ5Gnuw

//register patient
###
POST http://localhost:5005/register-patient
Content-Type: application/json

{
    "nik": "1234567821249095",
    "fullname": "Patient 1",
    "date_birth": "2024-03-12",
    "gender": "Patient 1",
    "address": "Patient 1",
    "work": "Patient 1",
    "phone": "012340576201",
    "statusPerkawinan": "",
    "agama": "",
    "riwayatAlergiObat": "",
    "riwayatAlergiMakanan": "",
    "riwayatAlergiLainya": ""
}

###
POST http://localhost:5005/admin/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "Admin1234!"
}

###
POST http://localhost:5005/patient/login
Content-Type: application/json

{
    "no_rm" : "000001",
    "nik" : "1234567821236497"
}

###
GET http://localhost:5005/fetch
Authorization: Bearer {{token}}
Content-Type: application/json

//Mount Dashboard
###
GET http://localhost:5005/amount-dashboard
Authorization: Bearer {{token}}
Content-Type: application/json

//Get ALL Patient
###
GET http://localhost:5005/patient?search=&sorting=ASC
Authorization: Bearer {{token}}
Content-Type: application/json

//Get Detail Patient
###
GET http://localhost:5005/patient/90b60f1b-88e8-478a-989b-602d29f09791
Authorization: Bearer {{token}}
Content-Type: application/json

//update pasien
###
PUT http://localhost:5005/patient/90b60f1b-88e8-478a-989b-602d29f09791
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nik": "1234567821236497",
    "fullname": "dicoba",
    "date_birth": "2024-03-15",
    "gender": "dicoba 1",
    "address": "dicoba 1",
    "work": "dicoba 1",
    "phone": "0123456891",
    "statusPerkawinan": "single",
    "agama": "islam",
    "riwayatAlergiObat": "tidak",
    "riwayatAlergiMakanan": "tidak",
    "riwayatAlergiLainya": "tidak"
}

//Get Role
###
GET http://localhost:5005/role
Authorization: Bearer {{token}}
Content-Type: application/json

//Create User Management
###
POST http://localhost:5005/user-management
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "fullname": "Dokter",
    "username": "dokter",
    "password": "Dokter1234!",
    "phone": "0867572732873",
    "email": "dokter@gmail.com",
    "roleId": "b3190fc1-5d23-497f-893f-8f64d2877c8b"
}

//Get User Management
###
GET http://localhost:5005/user-management?page=1&search=&sorting=DESC
Authorization: Bearer {{token}}
Content-Type: application/json

//Get Detail User Management
###
GET http://localhost:5005/user-management/ecff5d6c-1a44-4063-a746-0eeb7d2432ab
Authorization: Bearer {{token}}
Content-Type: application/json

//DeletelUser Management
###
DELETE  http://localhost:5005/user-management/b1474846-2c12-4e73-994a-de271eeff06e
Authorization: Bearer {{token}}
Content-Type: application/json



//Create Rekam Medis
###
POST http://localhost:5005/medical-Record
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "patientId": "90b60f1b-88e8-478a-989b-602d29f09791",
    //ngambil patinetId dari endpoint get ALL patientId. di ui tampilkan nama. di request pake id
    "pelayanan": "oke",
    "keluhan": "oke", 
    // keluhan yang diraskan
    "diagnosa": "oke", 
    //hasil analiysis dokter, termasuk penyakit dalam katagori apa
    "tindakan": "oke", 
    // tindakan yang dilakukan dokter dengan memberikan obat apa aja
    "biayaLayanan": 50000,
    "biayaObat": 10200,
    "statusPembayaran": "LUNAS"
}

//GET REKAM MEDIS
###
GET http://localhost:5005/medical-record?sorting=&search=
Authorization: Bearer {{token}}
Content-Type: application/json

//GET Detail REKAM MEDIS
###
GET http://localhost:5005/medical-record/ae19f029-a56a-46ce-aa0b-41bdfff153f7
Authorization: Bearer {{token}}
Content-Type: application/json

//Update Rekam Medis
###
PUT http://localhost:5005/medical-Record/8d0a5b11-8b5b-4b94-a4cf-c69f6959c4e0
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "patientId": "b671ea6c-c25d-4c31-9f29-51469d97361a",
    "pelayanan": "oke sip",
    "keluhan": "oke sip", 
    // keluhan yang diraskan
    "diagnosa": "oke sip", 
    //hasil analiysis dokter, termasuk penyakit dalam katagori apa
    "tindakan": "oke sip", 
    // tindakan yang dilakukan dokter dengan memberikan obat apa aja
    "biayaLayanan": 10500,
    "biayaObat": 10200,
    "statusPembayaran": "BELUM LUNAS"
    // jika biaya layanan, biaya obat, status pembayaran diupdate maka transaksi juga akan diupdate
}

//GET TRANSACTION
//Transaction hanya dapat get dan get detail
// untuk update dan create dihandle sama endpoint rekam medis 
// berikaitan antara tindakan yaitu isi obat dan biayaObat
// jika tindakan dirubah maka biaya obat juga akan berubah
// Jadi menyebabkan biaya transaksi juga berubah
###
GET http://localhost:5005/transaction
Authorization: Bearer {{token}}
Content-Type: application/json


###
POST http://localhost:5005/reservation
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "date": "2025-03-11",
    "diagnosis": "klinik gigi",
    "service": [{
        "name": "periksa gigi",
        "price": "50000"
    },{
        "name": "tambal gigi",
        "price": "10000"
    }],
    "user_id": ""
}

//LIST ALL RESERVATION ==> ONLY ADMIN 
###
GET http://localhost:5005/reservation
Authorization: Bearer {{token}}
Content-Type: application/json

//Detail Reservation by Patient
###
GET http://localhost:5005/reservation/2783ef0a-2ae2-4199-b20b-b989d518e4a1
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST http://localhost:5005/service
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "code": "CBTG1", 
   "name": "Cabut Gigi", 
   "price": "100000"
}
 
###
GET http://localhost:5005/service
Authorization: Bearer {{token}}
Content-Type: application/json

//chek patient by nik and date_birth IF old patient
###
GET http://localhost:5005/check-patient?&nik=1234567891236997&date_birth=2024-03-12
Authorization: Bearer {{token}}
Content-Type: application/json